config/routes.rb
Rails.application.routes.draw do
  
  get 'history' => 'info#history'
  
  resources :subscriptions do
    member do
      get :confirm
    end
  end
  
  resources :chapters do
    
    resources :subscriptions
    
    member do
      put :publish
    end
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end
  
  resources :accounts
  
  get '/logs', to: 'info#logs'
  
  get '/impressum', to: 'info#impressum'
  get '/datenschutz', to: 'info#datenschutz'
  
  root to: 'info#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  attr_accessor :checker
  
  belongs_to :previous, class_name: 'Chapter', optional: true
  belongs_to :author, class_name: 'Account', optional: true
  has_many :followers, class_name: 'Chapter', foreign_key: 'previous_id'
  has_many :subscriptions
  
  has_one_attached :audio_file
  
  after_initialize :fill_in_token
  
  validates :teaser, presence: true,
        length: { maximum: 255 }
  
  # --- SCOPES ---------------------------------
  
  scope :published, -> {
        where( status: 'public' )
        .order 'updated_at DESC' }
  scope :drafted, -> {
        where( status: 'draft' )
        .order 'updated_at DESC' }
  
  # --- INSTANCE METHODS -----------------------
  
  def to_param
    token
  end
  
  def fill_in_token
    self.token ||= Chapter.generate_token 5
  end
  
  def preview_text
    "#{author_name}: #{teaser}"
  end
  
  def author_name
    return 'niemand' unless author
    author.name_text
  end
  
  def draft?
    status == 'draft'
  end
  def published?
    status == 'public'
  end
  def hidden?
    status == 'hidden'
  end
  
  def checker_matches?
    !checker.blank? and
        checker.to_i == ( previous_chapters.size + previous_id.to_i )
  end
  
  def previous_chapters
    return [] if previous.blank?
    previous.previous_chapters << previous
  end
  
  def last_published
    return self if published?
    return nil if previous.blank?
    previous.last_published
  end
  
  def lines
    return [] if content.blank?
    content.split( "\n" ).compact
  end
  
  def teaser_words_count
    return 0 if teaser.blank?
    teaser.split( " " ).compact.size
  end
  
  def words_count
    result = teaser_words_count
    lines.each do |line|
      words = line.split( " " ).compact
      result += words.size
    end
    return result
  end
  
  def total_follower_count
    return 0 if followers.published.blank?
    followers.published.size + followers.published.inject( 0 ) { |sum,f| sum + f.total_follower_count }
  end
  
  def total_follower_words
    return 0 if followers.published.blank?
    followers.published.inject( 0 ) { |sum,f| sum + f.words_count + f.total_follower_words }
  end
  
  def longest_chapter_count
    return 1 if followers.published.blank?
    1 + followers.published.collect { |f| f.longest_chapter_count }.max
  end
  
  def longest_words
    return words_count if followers.published.blank?
    words_count + followers.published.collect { |f| f.longest_words }.max
  end
  
  def longest_branch_count
    return 0 if followers.published.blank?
    ( followers.published.size - 1 ) + followers.published.max { |a,b| a.longest_chapter_count <=> b.longest_chapter_count }.longest_branch_count
  end
  
  def total_branch_count
    return 0 if followers.published.blank?
    ( followers.published.size - 1 ) + followers.published.inject( 0 ) { |sum,f| sum + f.total_branch_count }
  end
  
  def unique_subscriptions
    result = []
    
    # add previous chapters
    previous_chapters.each do |chapter|
      chapter.subscriptions.each do |subscription|
        result << subscription unless result.detect { |s|
            s.email == subscription.email }
      end
    end
    
    # add subscriptions for this chapter
    subscriptions.each do |subscription|
      result << subscription unless result.detect { |s|
          s.email == subscription.email }
    end
    return result
  end
  
  # --- CLASS METHODS --------------------------
  
  def self.generate_token( in_length = 10, with_chars = false )
    result = ''
    # erstes Zeichen aus "sicheren" Zeichen
    random_index = rand( TOKEN_LETTERS.size )
    result += TOKEN_LETTERS[ random_index ]
    
    ( in_length - 1 ).times do
      if with_chars
        random_index = rand( TOKEN_CHARS.size )
        result += TOKEN_CHARS[ random_index ]
      else
        random_index = rand( TOKEN_LETTERS.size )
        result += TOKEN_LETTERS[ random_index ]
      end
    end
    return result
  end
  
  # --- CONSTANTS ------------------------------
  
  TOKEN_LETTERS = %w( 2 3 4 5 6 7 8 9 a b c d e f h i j k m n p q r s t u v w x y z A B C D E F H K L M N P Q R S T U V W X Y Z )
  TOKEN_CHARS = TOKEN_LETTERS.dup | %w( ! $ % & / = ? + * # < > : ) << '"' << '§' << '(' << ')' << '.'
  
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  skip_before_action :authorize, only: [ :index, :show, :new, :create ]
  before_action :set_chapter, only: [ :publish, :show, :edit, :update, :destroy ]
  before_action :check_access, only: [ :publish, :edit, :update, :destroy ]
  
  # --- CUSTOM METHODS -------------------------
  
  # PATCH/PUT /chapters/1/publish
  # PATCH/PUT /chapters/1/publish.js
  def publish
    redirect_to @chapter, alert: 'Nicht dein Kapitel, sorry!' if current_account != @chapter.author and return
    
    respond_to do |format|
      if @chapter.update_attribute :status, 'public'
        # notify prevoius chapter author
        ChapterMailer.published( @chapter.previous, @chapter, url_for( @chapter ) + "#ch#{@chapter.token}" ).deliver_later
        # notify all prevoius chapter authors
        if @chapter.previous
          @chapter.previous.previous_chapters.each do |chapter|
            ChapterMailer.continued( chapter, @chapter, url_for( @chapter ) + "#ch#{@chapter.token}" ).deliver_later
          end
        end
        
        format.html { redirect_to url_for( @chapter ) + "#ch#{@chapter.token}_actions", notice: 'Kapitel erfolgreich gespeichert.' }
        format.json { render :show, status: :ok, location: @chapter }
        
        write_log 'publish_chapter', nil, @chapter
        
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # --- STANDARD CRUD MEHTODS ------------------
  
  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.published.where( 'previous_id IS NULL' ).shuffle
    @max_word_count = @chapters.max_by { |c| c.longest_words }.longest_words
    logger.debug "--@max_word_count:#{@max_word_count}"
    
    write_log 'index_chapter'
  end
  
  # GET /chapters/1
  # GET /chapters/1.json
  def show
    redirect_to chapter_path( @chapter.last_published ) + "#ch#{@chapter.last_published.token}" and return unless @chapter.published? or own_chapter?
    
    @previous_chapters = @chapter.previous_chapters
    @published_followers = @chapter.followers.published
    @my_followers = @chapter.followers.select { |c| c.author == current_account }
    @followers = @published_followers | @my_followers
    
    write_log 'show_chapter', nil, @chapter
  end
  
  # GET /chapters/new
  def new
    @previous = Chapter.where( token: params[ :previous_token ] ).first
    if @previous
      @chapter = @previous.followers.build
    else
      @chapter = Chapter.new
    end
    
    @previous_chapters = @chapter.previous_chapters
  end
  
  # GET /chapters/1/edit
  def edit
    @previous_chapters = @chapter.previous_chapters
  end
  
  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new chapter_params
    redirect_to chapters_path, notice: 'Du hast die Checker-Frage vergessen, sorry!' and return unless @chapter.checker_matches?
    
    @chapter.status = 'draft'
    @chapter.author = current_account if current_account
    
    respond_to do |format|
      if @chapter.save
        session[ :last_chapter_id ] = @chapter.id
        @previous_chapters = @chapter.previous_chapters
        
        if @chapter.author and @chapter.author.email
          ChapterMailer.created( @chapter ).deliver_later
        end
        
        format.html do
          if current_account
            redirect_to edit_chapter_path( @chapter ), notice: 'Chapter was successfully created.'
          
          else
            redirect_to new_account_path, notice: 'Chapter was successfully created.'
          end
        end
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to url_for( @chapter ) + "#ch#{@chapter.token}_teaser", notice: 'Kapitel wurde erfolgreich geändert.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    redirect_target = @chapter.author
    @chapter.destroy
    
    respond_to do |format|
      format.html { redirect_to redirect_target, notice: 'Kapitel wurde gelöscht.' }
      format.json { head :no_content }
    end
  end
  
private

  # Use callbacks to share common setup or constraints between actions.
  def set_chapter
    @chapter = Chapter.where( token: params[ :id ] ).first
    redirect_to( chapters_path, alert: 'Dieses Kapitel wurde nicht gefunden! Bitte überprüfe deinen Link.' ) and return unless @chapter.is_a? Chapter
  end
  
  def own_chapter?
    @chapter and @chapter.author == current_account
  end
  
  # Redirect to login if not owner
  def check_access
    redirect_to( login_path, alert: 'Not your chapter, sorry!' ) and return unless own_chapter?
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def chapter_params
    params.require( :chapter )
        .permit( :teaser, :status, :previous_id, :content, :audio_file, :checker )
  end
  
end

app/helpers/chapters_helper.rb
module ChaptersHelper
  
  def h_allow_new_chapter?
    false
  end
  
end

app/views/chapters/_chapter_detail.html.haml
- is_previous = h_partial_init( is_previous, false )

.chapter_detail{ class: chapter.status, id: "ch#{chapter.token}" }
  .teaser{ id: "ch#{chapter.token}_teaser" }
    - if chapter.draft?
      .draft_label Entwurf
    
    = chapter.teaser
  
  .text_content
    = h_markdown chapter.content
    
  - if chapter.audio_file.attached?
    .audio_file
      %audio{ controls: true, src: url_for( chapter.audio_file ) }
      %p Hier kannst du dir den Text vorlesen lassen
    
  

- if is_previous
  .chapter_actions{ id: "ch#{chapter.token}_actions" }
    = link_to image_tag( 'icon_infos.png' ), '#', class: 'icon visible', data: { action: 'show_hide', sel: "#ch#{chapter.token}_infos, #ch#{chapter.token}_hidden_actions" }
    .hidden_actions{ id: "ch#{chapter.token}_hidden_actions" }
      .separator &nbsp;|&nbsp;
      = link_to 'Hierher zurück', url_for( chapter ) + "#ch#{chapter.token}_actions"
    
  
  = render 'chapters/chapter_infos', chapter: chapter

app/views/chapters/_chapter_graph.html.haml
%tr
  %td.chapter_bar{ class: "level#{level}" }
    = image_tag 'clear.gif', width: "#{(chapter.words_count.to_f / @max_word_count * 600).to_i - 5}", title: "#{chapter.author.name} - #{truncate chapter.teaser, length: 50} - #{chapter.words_count} Worte"
  
  %td.follower_bar{ class: "level#{level}" }
    %table.graph
      = render partial: 'chapter_graph',
            collection: chapter.followers.published,
            as: :chapter,
            locals: { level: level + 1 }
    
  

app/views/chapters/_chapter_infos.html.haml
.chapter_infos{ id: "ch#{chapter.token}_infos" }
  %p
    Dieses Kapitel wurde von
    - if chapter.author
      = link_to chapter.author_name, chapter.author
    - else
      niemandem
    
    geschrieben und am
    =l chapter.updated_at
    veröffentlicht. Es enthält
    = chapter.words_count
    Worte.
  
  %h3 Alle Kapitel bis hier
  %ul
    - chapter.previous_chapters.each do |previous|
      %li= link_to truncate( previous.teaser, length: 100 ), chapter_path( previous ) + "#ch#{previous.token}_teaser"
    
  

app/views/chapters/_chapter_list.html.haml
%ul.chapter_list
  - chapters.each do |chapter|
    %li.chapter_preview
      = link_to chapter.teaser, url_for( chapter ) + "#ch#{chapter.token}_teaser", class: 'chapter_link'
    
  

app/views/chapters/_chapter_preview_main.html.haml
= link_to chapter.teaser, chapter, class: 'chapter_link teaser'
.text= truncate( chapter.content, length: 255 )

.chapter_graph
  %table.graph
    = render 'chapter_graph',
          chapter: chapter,
          level: 1
  

.actions
  = link_to image_tag( 'icon_infos.png' ), '#', class: 'icon', data: { action: 'show_hide', sel: "#ch#{chapter.token}_infos" }

.infos{ id: "ch#{chapter.token}_infos" }
  = 1 + chapter.total_follower_count
  Kapitel mit
  = chapter.words_count + chapter.total_follower_words
  Worten.
  %br
  - if chapter.total_follower_count > chapter.longest_chapter_count
    Der längste Erzählstrang hat
    = chapter.longest_chapter_count
    Kapitel mit
    = chapter.longest_words
    Worten.
  - else
    Dies ist der längste Erzählstrang.
  
  - if chapter.longest_branch_count > 0
    %br
    Es gibt dort
    
    - if chapter.total_branch_count > chapter.longest_branch_count
      = pluralize chapter.longest_branch_count, 'Abzweigung'
      und insgesamt sogar
      = chapter.total_branch_count
      Abzweigungen.
    - else
      = pluralize( chapter.longest_branch_count, 'Abzweigung' ) + '.'
    
  
  %br
  Dieses Startkapitel wurde von
  - if chapter.author
    = link_to chapter.author_name, chapter.author
  - else
    niemandem
  
  geschrieben und am
  =l chapter.updated_at
  veröffentlicht.

app/views/chapters/_form.html.haml
= form_for @chapter do |f|
  - if @chapter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chapter.errors.count, "error")} prohibited this chapter from being saved:"
      %ul
        - @chapter.errors.full_messages.each do |message|
          %li= message
        
      
    
  
  = f.hidden_field :previous_id
  
  .field
    = f.label :teaser, 'Dein nächster Satz als Appetitanreger'
    = f.text_field :teaser
  
  .field
    = f.label :content, 'Dein Kapitel'
    = f.text_area :content, rows: 10
  
  .field
    = f.label :author
    = f.text_field :author
  
  .actions
    = f.submit 'Sichern', class: 'button'
    &nbsp;&nbsp;
    = cancel_action
  

app/views/chapters/_form_content.html.haml
= form_for @chapter do |f|
  - if @chapter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chapter.errors.count, "error")} prohibited this chapter from being saved:"
      %ul
        - @chapter.errors.full_messages.each do |message|
          %li= message
        
      
    
  
  = f.hidden_field :previous_id
  
  .field
    = f.label :teaser, 'Der Titel deiner Geschichte'
    = f.text_field :teaser
  
  .field
    = f.label :content, 'Der Text deines Kapitels'
    = f.text_area :content, rows: 10
  
  %p.help
    Wenn du länger schreiben möchtest, wäre es vielleicht besser, du beginnst in einem Textprogramm und kopierst den Text dann hier rein.
  
  .field
    = f.label :audio_file, 'Audio Datei des Textes (optional)'
    = f.file_field :audio_file
  
  .actions
    = f.submit 'Vorschau', class: 'button'
    &nbsp;&nbsp;
    = cancel_action
  

app/views/chapters/_form_teaser.html.haml
= form_for @chapter do |f|
  - if @chapter.errors.any?
    #error_explanation
      %h2= "#{@chapter.errors.count} Fehler verhindert, dass dieses Kapitel gesichert werden kann:"
      %ul
        - @chapter.errors.full_messages.each do |message|
          %li= message
        
      
    
  
  = f.hidden_field :previous_id
  
  .field
    - if @chapter.previous
      = f.label :teaser, 'Dein nächster Satz als Appetitanreger'
    - else
      = f.label :teaser, 'Der Titel deiner Geschichte'
    
    = f.text_area :teaser, rows: 3
  
  .field
    = f.label :checker, "Was ist #{@chapter.previous_chapters.size} plus #{@chapter.previous_id.to_i}?"
    = f.text_area :checker, placeholder: 'Müllschutzfrage ;-)'
  
  .actions
    = f.submit 'Starten', class: 'button'
    &nbsp;&nbsp;
    = cancel_action
  

app/views/chapters/edit.html.haml
.content
  - if @chapter.previous
    = render 'chapter_detail', chapter: @chapter.previous, is_previous: true
  
  %p.help
    Prima, nun kannst Du Dein Kapitel beginnen.
  
  %h5 Schreiben
  
  = render partial: 'form_content', locals: { cancel_action: link_to( 'Abbrechen', @chapter ) }
  

app/views/chapters/index.html.haml
- h_title 'Alle Fortsetzungsgeschichten'
- h_description "Lies eine der #{@chapters.size} Fortsetzungsgeschichten und schreibe sie weiter."

.content.chapter_index
  = render 'layouts/flashs'
  
  %h3
    Die
    = pluralize @chapters.size, 'Fortsetzungsgeschichte'
  
  - if h_allow_new_chapter?
    %p= link_to 'Neues Startkapitel schreiben...', new_chapter_path
  
  %ul.chapter_list.main
    - @chapters.each do |chapter|
      %li.chapter_preview
        = render 'chapter_preview_main', chapter: chapter
      
    
  

app/views/chapters/new.html.haml
- if @chapter.previous
  - link = url_for( @chapter.previous ) + "#ch#{@chapter.previous.token}_actions"
- else
  - link = chapters_path

- cancel_action = link_to 'Abbrechen', link

.content
  - if @chapter.previous
    = render 'chapter_detail', chapter: @chapter.previous, is_previous: true
    
    %p.help
      Du kannst die Geschichte fortsetzen und dein eigenes Kapitel schreiben.
    
    %p.help
      Zuerst schreibst du einen Satz, der als Appetitanreger für ein Weiterlesen unter dem letzten Kapitel angezeigt wird.
    
    %br
    %h5
      Ein neues Kapitel
      - if @previous_chapters
        = @previous_chapters.size + 1
      
      beginnen
    
  - else
    %p.help
      Beginne deine neue Geschichte mit einem spannenden Titel.
    
  
  = render 'form_teaser', cancel_action: cancel_action
  

app/views/chapters/show.html.haml
- h_title @chapter.teaser
- h_description @chapter.lines.first

.content
  = render 'layouts/flashs'
  
  %h3.starter
    Eine Geschichte in
    = pluralize @previous_chapters.size + 1, 'Kapitel'
  
  - unless @previous_chapters.blank?
    .previous_chapters_block
      %h2 Was bisher geschah…
      - @previous_chapters.each_with_index do |chapter, i|
        = link_to chapter, class: 'previous_chapter_link' do
          .index= ( i + 1 ) < 10 ? "0#{i + 1}" : ( i + 1 ).to_s
          .link= chapter.teaser
        
      
    
  
  = render partial: 'chapter_detail', locals: { chapter: @chapter }
  
  - unless @chapter.unique_subscriptions.blank?
    %p.subscription_info
      = @chapter.unique_subscriptions.size
      = "Mensch#{@chapter.unique_subscriptions.size > 1 ? 'en' : ''}"
      = "wart#{@chapter.unique_subscriptions.size > 1 ? 'en' : 'et'}"
      auf das nächste Kapitel...
    
  
  .chapter_actions{ id: "ch#{@chapter.token}_actions" }
    = link_to image_tag( 'icon_infos.png' ), '#', class: 'icon', data: { action: 'show_hide', sel: "#ch#{@chapter.token}_infos" }
    
    - if @followers.size == 1
      = link_to 'Weiterlesen', url_for( @followers.first ) + "#ch#{@followers.first.token}", class: 'separated'
    
    - if @followers.size > 1
      = link_to 'Weiterlesen', '#', data: { action: 'show_hide', sel: "#ch#{@chapter.token}_followers" }, class: 'separated'
    
    - if @followers.blank?
      = link_to 'Weiterlesen', new_chapter_subscription_path( @chapter ) +  "#ch#{@chapter.token}_subscription", class: 'separated'
    
    - if @chapter.published?
      = link_to 'Weiterschreiben', new_chapter_path( previous_token: @chapter.token ) + "#ch#{@chapter.token}_actions", class: 'separated'
    - else
      = link_to 'Bearbeiten', edit_chapter_path( @chapter ) + "#ch#{@chapter.token}_actions}", class: 'separated'
      = link_to 'Veröffentlichen', publish_chapter_path( @chapter ), method: :put, data: { confirm: "Willst Du das Kapitel wirklich veröffentlichen?\nDas ist unwiderruflich..." }, class: 'separated'
      = link_to 'Löschen', @chapter, method: :delete, data: { confirm: "Willst Du das Kapitel '#{@chapter.teaser.truncate 40 }' wirklich löschen?\nDie Aktion kann nicht rückgängig gemacht werden!" }, class: 'separated danger'
    
  
  = render 'chapter_infos', chapter: @chapter
  
  - if @followers.size > 1
    .chapter_followers{ id: "ch#{@chapter.token}_followers" }
      %h5
        Wie es weitergehen könnte...
      
      %ul.chapter_list
        - @followers.each do |follower|
          %li.chapter_preview{ class: follower.status }
            = link_to url_for( follower ) + "#ch#{follower.token}_teaser", class: 'chapter_link' do
              .teaser= follower.teaser
              .infos
                - if follower.longest_chapter_count > 1
                  %span{ title: "hier weitere Kapitel: #{follower.longest_chapter_count}" }
                    = "#{follower.longest_chapter_count}K"
                  
                  \|
                
                %span{ title: "hier weitere Worte gesamt: #{follower.longest_words}" }
                  = "#{follower.longest_words}W"
                
                - if follower.total_branch_count > 0
                  \|
                  %span{ title: "hier weitere Abzweigungen: #{follower.total_branch_count}" }
                    = "#{follower.total_branch_count}A"
                  
                
              
            
          
        
      
    
  