config/routes.rb
Rails.application.routes.draw do
  
  get 'history' => 'info#history'
  
  resources :subscriptions do
    member do
      get :confirm
    end
  end
  
  resources :chapters do
    
    resources :subscriptions
    
    member do
      put :publish
    end
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end
  
  resources :accounts
  
  get '/logs', to: 'info#logs'
  
  get '/impressum', to: 'info#impressum'
  get '/datenschutz', to: 'info#datenschutz'
  
  root to: 'info#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  skip_before_action :authorize, only: [ :impressum, :datenschutz, :history, :index ]
  
  
  def history
    @chapters = Chapter.published.order updated_at: :desc
    @date = Time.zone.now.at_midnight
  end
  
  # --- STANDARD CRUD MEHTODS ------------------
  
  def index
    write_log 'index'
  end
  
  def logs
    logger.debug "-- Time.zone.now: #{Time.zone.now}"
    @today = Time.zone.now.at_beginning_of_day
    logger.debug "-- @today: #{@today}"
    @this_week = @today.at_beginning_of_week
    logger.debug "-- @this_week: #{@this_week}"
    
    @requests_d0 = get_requests_between @today, @today + 24.hours
    @requests_d1 = get_requests_between @today - 24.hours, @today
    @requests_d2 = get_requests_between @today - 48.hours, @today - 24.hours
    @requests_d3 = get_requests_between @today - 72.hours, @today - 48.hours
    @requests_d4 = get_requests_between @today - 96.hours, @today - 72.hours
    
    @requests_w0 = get_requests_between @this_week, @this_week + 1.week
    @requests_w1 = get_requests_between @this_week - 1.week, @this_week
    @requests_w2 = get_requests_between @this_week - 2.weeks, @this_week - 1.week
    @requests_w3 = get_requests_between @this_week - 3.weeks, @this_week - 2.week
    @requests_w4 = get_requests_between @this_week - 4.weeks, @this_week - 3.week
    logger.debug "-- d0:#{@requests_d0.size}"
    logger.debug "-- d1:#{@requests_d1.size}"
    logger.debug "-- d2:#{@requests_d2.size}"
    logger.debug "-- w0:#{@requests_w0.size}"
    logger.debug "-- w1:#{@requests_w1.size}"
    logger.debug "-- w2:#{@requests_w2.size}"
    
    @entities = @requests_d0.
        collect { |r| r.entity }
    @entities |= @requests_d1.collect { |r| r.entity }
    @entities |= @requests_d2.collect { |r| r.entity }
    @entities |= @requests_d3.collect { |r| r.entity }
    @entities |= @requests_d4.collect { |r| r.entity }
    @entities |= @requests_w0.collect { |r| r.entity }
    @entities |= @requests_w1.collect { |r| r.entity }
    @entities |= @requests_w2.collect { |r| r.entity }
    @entities |= @requests_w3.collect { |r| r.entity }
    @entities |= @requests_w4.collect { |r| r.entity }
    @entities.uniq!
    @entities.compact!
    logger.debug "-- @entities.size:#{@entities.size}"
    
    @requests = @entities.collect { |e| [
          @requests_d0.detect { |r| r.entity == e },
          @requests_d1.detect { |r| r.entity == e },
          @requests_d2.detect { |r| r.entity == e },
          @requests_d3.detect { |r| r.entity == e },
          @requests_d4.detect { |r| r.entity == e },
          @requests_w0.detect { |r| r.entity == e },
          @requests_w1.detect { |r| r.entity == e },
          @requests_w2.detect { |r| r.entity == e },
          @requests_w3.detect { |r| r.entity == e },
          @requests_w4.detect { |r| r.entity == e } ] }
    #debugger
    @requests.sort! { |a,b|
        b.max_by { |r|
            r.blank? ? 0 : r.amount }.amount <=>
        a.max_by { |r|
            r.blank? ? 0 : r.amount }.amount }
  end
  
private
  
  def get_requests_between( in_time_a, in_time_b )
    Log.find_by_sql [ 'SELECT count(*) AS amount, entity_type, entity_id
        FROM logs
        WHERE created_at > :t1 AND created_at <= :t2
        GROUP BY entity_type, entity_id
        ORDER by amount DESC', t1: in_time_a, t2: in_time_b ]
  end
  
end

app/helpers/info_helper.rb
module InfoHelper
  
  def h_quot in_a, in_b
    ( 1.0 * in_a / in_b * 100 ).round - 100 if in_b > 0
  end
  
  def h_quot_class( in_a, in_b )
    quot = h_quot in_a, in_b
    value_class = quot.to_f > 0 ?
        'positive' : ( quot.to_f < 0 ?
            'negative' : 'zero' )
    return "number percentage #{value_class}"
  end
  
end

app/views/info/_history_preview.html.haml
.infos{ id: "ch#{chapter.token}_infos" }
  - if chapter.author
    = link_to chapter.author_name, chapter.author
  - else
    niemand
  
  schrieb ein neues Kapitel mit
  = chapter.words_count
  Worten:

= link_to chapter.teaser, chapter_path( chapter ) + "#ch#{chapter.token}_teaser", class: 'teaser'

.text_content
  = h_markdown truncate( chapter.content, length: 255 )

app/views/info/_impressum.html.haml
%h3 Impressum
%p
  = image_tag 'impressum.png', class: 'impressum'

%h4 Hinweis gemäß Online-Streitbeilegungs-Verordnung
%p
  Nach geltendem Recht sind wir verpflichtet, Verbraucher auf die Existenz der Europäischen Online-Streitbeilegungs-Plattform hinzuweisen, die für die Beilegung von Streitigkeiten genutzt werden kann, ohne dass ein Gericht eingeschaltet werden muss. Für die Einrichtung der Plattform ist die Europäische Kommission zuständig. Die Europäische Online-Streitbeilegungs-Plattform ist hier zu finden:
  = link_to 'http://ec.europa.eu/odr',
        'http://ec.europa.eu/odr',
        target: "_blank", rel: "nofollow"
  %br
  Unsere E-Mail lautet
  = image_tag 'email.png', class: 'impressum_email'

%p
  Wir weisen aber darauf hin, dass wir nicht bereit sind, uns am Streitbeilegungsverfahren im Rahmen der Europäischen Online-Streitbeilegungs-Plattform zu beteiligen. Nutzen Sie zur Kontaktaufnahme bitte unsere obige E-Mail und Telefonnummer.

%h4 Hinweis gemäß Verbraucherstreitbeilegungsgesetz (VSBG)
%p
  Wir sind nicht bereit und verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.

%br
%h4 Disclaimer – rechtliche Hinweise
%h5 § 1 Warnhinweis zu Inhalten
%p
  Die kostenlosen und frei zugänglichen Inhalte dieser Webseite wurden mit größtmöglicher Sorgfalt erstellt. Der Anbieter dieser Webseite übernimmt jedoch keine Gewähr für die Richtigkeit und Aktualität der bereitgestellten kostenlosen und frei zugänglichen journalistischen Ratgeber und Nachrichten. Namentlich gekennzeichnete Beiträge geben die Meinung des jeweiligen Autors und nicht immer die Meinung des Anbieters wieder. Allein durch den Aufruf der kostenlosen und frei zugänglichen Inhalte kommt keinerlei Vertragsverhältnis zwischen dem Nutzer und dem Anbieter zustande, insoweit fehlt es am Rechtsbindungswillen des Anbieters.

%h5 § 2 Externe Links
%p
  Diese Website enthält Verknüpfungen zu Websites Dritter ("externe Links"). Diese Websites unterliegen der Haftung der jeweiligen Betreiber. Der Anbieter hat bei der erstmaligen Verknüpfung der externen Links die fremden Inhalte daraufhin überprüft, ob etwaige Rechtsverstöße bestehen. Zu dem Zeitpunkt waren keine Rechtsverstöße ersichtlich. Der Anbieter hat keinerlei Einfluss auf die aktuelle und zukünftige Gestaltung und auf die Inhalte der verknüpften Seiten. Das Setzen von externen Links bedeutet nicht, dass sich der Anbieter die hinter dem Verweis oder Link liegenden Inhalte zu Eigen macht. Eine ständige Kontrolle der externen Links ist für den Anbieter ohne konkrete Hinweise auf Rechtsverstöße nicht zumutbar. Bei Kenntnis von Rechtsverstößen werden jedoch derartige externe Links unverzüglich gelöscht.

%h5 § 3 Urheber- und Leistungsschutzrechte
%p
  Die auf dieser Website veröffentlichten Inhalte unterliegen dem deutschen Urheber- und Leistungsschutzrecht. Jede vom deutschen Urheber- und Leistungsschutzrecht nicht zugelassene Verwertung bedarf der vorherigen schriftlichen Zustimmung des Anbieters oder jeweiligen Rechteinhabers. Dies gilt insbesondere für Vervielfältigung, Bearbeitung, Übersetzung, Einspeicherung, Verarbeitung bzw. Wiedergabe von Inhalten in Datenbanken oder anderen elektronischen Medien und Systemen. Inhalte und Rechte Dritter sind dabei als solche gekennzeichnet. Die unerlaubte Vervielfältigung oder Weitergabe einzelner Inhalte oder kompletter Seiten ist nicht gestattet und strafbar. Lediglich die Herstellung von Kopien und Downloads für den persönlichen, privaten und nicht kommerziellen Gebrauch ist erlaubt.

%p
  Die Darstellung dieser Website in fremden Frames ist nur mit schriftlicher Erlaubnis zulässig.

%h5 § 4 Besondere Nutzungsbedingungen
%p
  Soweit besondere Bedingungen für einzelne Nutzungen dieser Website von den vorgenannten Paragraphen abweichen, wird an entsprechender Stelle ausdrücklich darauf hingewiesen. In diesem Falle gelten im jeweiligen Einzelfall die besonderen Nutzungsbedingungen.

%br
%p
  Quelle:
  = link_to 'Impressum Vorlage von JuraForum.de',
        'https://www.juraforum.de/impressum-generator/',
        target: '_blank', rel: 'nofollow'

app/views/info/datenschutz.html.haml
- h_title 'skribi - Datenschutz'

.content
  = render 'datenschutz'

app/views/info/history.html.haml
- h_title 'skribi - Was bisher geschah...'
- h_description "Eine chronologische Auflistung der letzten verfassten Kapitel und Autor*innen."

.content
  - unless alert.blank?
    .callout.warning
      %p= alert
    
  
  - unless notice.blank?
    .callout.success
      %p= notice
    
  
  %h5
    Was bisher geschah...
  
  %ul.history_list
    - @chapters.each do |chapter|
      - if @date != chapter.updated_at.at_midnight
        %li.date=l chapter.updated_at, format: :short_day
        - @date = chapter.updated_at.at_midnight
      
      %li.history_preview
        = render 'history_preview', chapter: chapter
      
    
  

app/views/info/impressum.html.haml
- h_title 'skribi - Impressum'

.content
  = render 'impressum'

app/views/info/index.html.haml
- h_main_nav
- h_title 'skribi - Eine Website für Fortsetzungsgeschichten'

.content
  %p
    Schreiben.<br/>
    Weiterschreiben.<br/>
    Noch weiter schreiben.
  
  %p
    Und lesen.
  
  %h1 Eine Website für Fortsetzungsgeschichten.
  %p.help
    Jemand beginnt und veröffentlicht ein kurzes Kapitel.<br/>
    Alle, die Lust haben, können die Geschichte dort fortsetzen.<br/>
  
  %p.help
    So einfach!
  
  
  %p
    = link_to 'Die Geschichten lesen...', chapters_path, class: 'big_link'
    %br
    = link_to 'Eine neue Geschichte schreiben...', new_chapter_path, class: 'big_link'
  %p
    = link_to 'Was bisher geschah...', history_path
    %span.separator &nbsp;|&nbsp;
    = link_to 'Mehr Hilfe bitte...', Chapter.find_by( token: 'hilfe' )
    %span.separator &nbsp;|&nbsp;
    = link_to 'skribi_io bei Twitter...', 'https://twitter.com/skribi_io', target: '_blank'
  

app/views/info/logs.html.haml
- h_title 'Statistiken Abrufe'
- h_description 'Aktuelle Seitenabrufe der Website'

.content.statistic_detail
  %h1.title
    Aktuelle Abrufe vom
    =l @today, format: :short_day
  
  .description
    %p Aktuelle Seitenabrufe der Website.
  
  .request_statistics
    %table
      %thead
        %tr
          %th.number heute
          %th.number{ colspan: 2 } gestern
          %th.number{ colspan: 2 }=l ( @today - 2.days ), format: :only_day
          %th.number{ colspan: 2 }=l ( @today - 3.days ), format: :only_day
          %th.number.separating{ colspan: 2 }=l ( @today - 4.days ), format: :only_day
          %th.number Diese<br>Woche
          %th.number{ colspan: 2 } Letzte<br>Woche
          %th.number{ colspan: 2 } Woche<br>davor
          %th.number{ colspan: 2 } Woche<br>davor
          %th.number{ colspan: 2 } Woche<br>davor
          %th Entität
          %th Inhalt
        
       
      
      %tbody
        %tr
          - d0 = @requests.inject( 0 ) { |sum,r| sum + ( r.first ? r.first.amount : 0 ) }
          - d1 = @requests.inject( 0 ) { |sum,r| sum + ( r.second ? r.second.amount : 0 ) }
          - d2 = @requests.inject( 0 ) { |sum,r| sum + ( r.third ? r.third.amount : 0 ) }
          - d3 = @requests.inject( 0 ) { |sum,r| sum + ( r.fourth ? r.fourth.amount : 0 ) }
          - d4 = @requests.inject( 0 ) { |sum,r| sum + ( r.fifth ? r.fifth.amount : 0 ) }
          - w0 = @requests.inject( 0 ) { |sum,r| sum + ( r[5] ? r[5].amount : 0 ) }
          - w1 = @requests.inject( 0 ) { |sum,r| sum + ( r[6] ? r[6].amount : 0 ) }
          - w2 = @requests.inject( 0 ) { |sum,r| sum + ( r[7] ? r[7].amount : 0 ) }
          - w3 = @requests.inject( 0 ) { |sum,r| sum + ( r[8] ? r[8].amount : 0 ) }
          - w4 = @requests.inject( 0 ) { |sum,r| sum + ( r[9] ? r[9].amount : 0 ) }
          
          %td.number= d0
          %td{ class: h_quot_class( d0, d1 ) }= "#{h_quot d0, d1}%" if d1 > 0
          %td.number= d1
          %td{ class: h_quot_class( d1, d2 ) }= "#{h_quot d1, d2}%" if d2 > 0
          %td.number= d2
          %td{ class: h_quot_class( d2, d3 ) }= "#{h_quot d2, d3}%" if d3 > 0
          %td.number= d3
          %td{ class: h_quot_class( d3, d4 ) }= "#{h_quot d3, d4}%" if d4 > 0
          %td.number.separating= d4
          
          %td.number= w0
          %td{ class: h_quot_class( w0, w1 ) }= "#{h_quot w0, w1}%" if w1 > 0
          %td.number= w1
          %td{ class: h_quot_class( w1, w2 ) }= "#{h_quot w1, w2}%" if w2 > 0
          %td.number= w2
          %td{ class: h_quot_class( w2, w3 ) }= "#{h_quot w2, w3}%" if w3 > 0
          %td.number= w3
          %td{ class: h_quot_class( w3, w4 ) }= "#{h_quot w3, w4}%" if w4 > 0
          %td.number= w4
          
          %td.entity alle
          %td &nbsp;
        
        - @requests.each do |request|
          %tr
            - #logger.debug "-- request:#{request.to_yaml}"
            - d0 = request.first ? request.first.amount : 0
            - d1 = request.second ? request.second.amount : 0
            - d2 = request.third ? request.third.amount : 0
            - d3 = request.fourth ? request.fourth.amount : 0
            - d4 = request.fifth ? request.fifth.amount : 0
            - w0 = request[5] ? request[5].amount : 0
            - w1 = request[6] ? request[6].amount : 0
            - w2 = request[7] ? request[7].amount : 0
            - w3 = request[8] ? request[8].amount : 0
            - w4 = request[9] ? request[9].amount : 0
            - request_with_entity = request.detect { |r| !r.blank? and !r.entity.blank? }
            - #logger.debug "-- request_with_entity:#{request_with_entity.to_yaml}"
            - #logger.debug "-- request_with_entity.entity:#{request_with_entity.entity.to_yaml}"
            
            %td.number= d0 if d0 > 0
            %td.number{ class: h_quot_class( d0, d1 ) }= "#{h_quot d0, d1}%" if d1 > 0
            %td.number= d1 if d1 > 0
            %td.number{ class: h_quot_class( d1, d2 ) }= "#{h_quot d1, d2}%" if d2 > 0
            %td.number= d2 if d2 > 0
            %td.number{ class: h_quot_class( d2, d3 ) }= "#{h_quot d2, d3}%" if d3 > 0
            %td.number= d3 if d3 > 0
            %td.number{ class: h_quot_class( d3, d4 ) }= "#{h_quot d3, d4}%" if d4 > 0
            %td.number.separating= d4 if d4 > 0
            
            %td.number= w0 if w0 > 0
            %td.number{ class: h_quot_class( w0, w1 ) }= "#{h_quot w0, w1}%" if w1 > 0
            %td.number= w1 if w1 > 0
            %td.number{ class: h_quot_class( w1, w2 ) }= "#{h_quot w1, w2}%" if w2 > 0
            %td.number= w2 if w2 > 0
            %td.number{ class: h_quot_class( w2, w3 ) }= "#{h_quot w2, w3}%" if w3 > 0
            %td.number= w3 if w3 > 0
            %td.number{ class: h_quot_class( w3, w4 ) }= "#{h_quot w3, w4}%" if w4 > 0
            %td.number= w4 if w4 > 0
            
            %td.entity= link_to( request_with_entity.entity_type, request_with_entity.entity )
            %td
              .preview_text
                = truncate request_with_entity.entity.preview_text, length: 100
            
          
        
      
    
  