config/routes.rb
Rails.application.routes.draw do
  
  get 'history' => 'info#history'
  
  resources :subscriptions do
    member do
      get :confirm
    end
  end
  
  resources :chapters do
    
    resources :subscriptions
    
    member do
      put :publish
    end
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end
  
  resources :accounts
  
  get '/logs', to: 'info#logs'
  
  get '/impressum', to: 'info#impressum'
  get '/datenschutz', to: 'info#datenschutz'
  
  root to: 'info#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flashs.html.haml
- unless alert.blank?
  .callout.warning
    %p= alert
  

- unless notice.blank?
  .callout.success
    %p= notice
  

app/views/layouts/_footer.html.haml
%footer{ role: "contentinfo"}
  %p
    = "© #{Time.zone.now.year} Skribi."
    Alle Rechte vorbehalten.
    &bull;
    = link_to 'Login', login_path
    &bull;
    = link_to 'Impressum', impressum_path
    &bull;
    = link_to 'Datenschutz', datenschutz_path
  

app/views/layouts/_navbar.html.haml
.nav_bar
  = link_to image_tag( 'logo_wort.png', alt: 'skribi Logo' ), root_url, class: 'logo_wort'
  
  - if current_account
    = link_to 'Logout', logout_path
    = link_to 'Ich', current_account
  
  = link_to '...was ist das?', root_path

app/views/layouts/_navbar_main.html.haml
.nav_bar.main
  = image_tag 'logo_wort.png', class: 'logo_wort'
  
  - if current_account
    = link_to 'Ich', current_account
    = link_to 'Logout', logout_path
  - else
    = link_to 'Login', login_path
  

app/views/layouts/_opengraph.html.haml
%meta{ property: "og:type", content: h_og_type }
%meta{ property: "og:title", content: h_og_title }
%meta{ property: "og:description", content: h_og_description }
%meta{ property: "og:image", content: h_og_image }
%meta{ property: "twitter:card", content: h_og_type }
%meta{ property: "twitter:site", content: "@skribi_io" }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="msapplication-TileColor" content="#eeeeee" />
    
    <%= render 'layouts/opengraph' %>
    
    <link rel="icon" href="/assets/logo_skribi_q96.png" />
    <link rel="apple-touch-icon-precomposed" href="/assets/logo_skribi_q152.jpg" />
    <link rel="icon" sizes="152x152" href="/assets/logo_skribi_q152.jpg" />
    <link rel="icon" sizes="192x192" href="/assets/logo_skribi_q192.jpg" />
    
    <title><%= h_seitentitel %></title>
    
    <%= stylesheet_link_tag 'application',
          'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'modernizr' %>
    <%= csrf_meta_tags %>
  </head>
  
  <body>
    <main>
      <% if h_main_nav? %>
        <%= render 'layouts/navbar_main' %>
      <% else %>
        <%= render 'layouts/navbar' %>
      <% end %>
      
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
    
    <%= javascript_include_tag 'application',
          'data-turbolinks-track': 'reload' %>
  </body>
</html>