config/routes.rb
Rails.application.routes.draw do
  
  get 'history' => 'info#history'
  
  resources :subscriptions do
    member do
      get :confirm
    end
  end
  
  resources :chapters do
    
    resources :subscriptions
    
    member do
      put :publish
    end
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end
  
  resources :accounts
  
  get '/logs', to: 'info#logs'
  
  get '/impressum', to: 'info#impressum'
  get '/datenschutz', to: 'info#datenschutz'
  
  root to: 'info#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
# ----------------------------------------------
class Account < ApplicationRecord
  has_secure_password
  has_many :chapters, class_name: 'Chapter', foreign_key: 'author_id'
  
  after_destroy :ensure_an_admin_remains
  
  validates :email, presence: true,
        uniqueness: true
  
  class Error < StandardError
  end
  
  def preview_text
    name_text
  end
  
  def name_text
    !name.blank? ? name : 'unbekannte Person'
  end
  
private
  
  def ensure_an_admin_remains
    if Account.count.zero?
      raise Error.new "Can't delete last user"
    end
  end
  
end

app/controllers/accounts_controller.rb
# ----------------------------------------------
class AccountsController < ApplicationController
  skip_before_action :authorize, only: [ :new, :create, :show ]
  before_action :set_account, only: [ :show, :edit, :update, :destroy ]
  before_action :check_access, only: [ :edit, :update, :destroy ]
  
  
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.order 'created_at DESC'
  end
  
  # GET /accounts/1
  # GET /accounts/1.json
  def show
    write_log 'show_account', nil, @account
  end
  
  # GET /accounts/new
  def new
    @account = Account.new
  end
  
  # GET /accounts/1/edit
  def edit
  end
  
  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new account_params
    @account.status = 'new'
    
    respond_to do |format|
      if @account.save
        # log it in
        session[ :account_id ] = @account.id
        
        if session[ :last_chapter_id ]
          @chapter = Chapter.find session[ :last_chapter_id ]
          @chapter.author ||= @account
          @chapter.save!
          session[ :last_chapter_id ] = nil
          
          format.html { redirect_to edit_chapter_path( @chapter ), notice: "Account #{@account.name} was successfully created." }
          
        else
          format.html { redirect_to root_url, notice: "Account #{@account.name} was successfully created." }
        end
        format.json { render :show,
              status: :created,
              location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors,
              status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    redirect_to root_url, alert: 'Nicht Dein Zugang, sorry!' and return unless current_account == @account
    
    respond_to do |format|
      if @account.update account_params
        format.html { redirect_to @account,
              notice: "Account #{@account.name} was successfully updated." }
        format.json { render :show,
              status: :ok,
              location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors,
              status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    redirect_to root_url, alert: 'Nicht Dein Zugang, sorry!' and return unless current_account == @account
    
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  rescue_from 'Account::Error' do |ex|
    redirect_to accounts_url,
          notice: ex.message
  end
  
private
  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end
  
  # Redirect to login if not owner
  def check_access
    redirect_to( login_path, alert: 'Not your account, sorry!' ) and return unless @account == current_account
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require( :account ).permit( :email, :name, :password, :password_confirmation, :description, :url )
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.haml
= form_with model: account, local: true do |f|
  - if account.errors.any?
    #error_explanation
      %h2= "#{pluralize(account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |message|
          %li= message
        
      
    
  
  .field
    = f.label :name, 'Dein Name'
    = f.text_field :name, placeholder: 'Hanna Muster'
  
  .field
    = f.label :description, 'Was Du über Dich sagen möchtest'
    = f.text_area :description, rows: 5
  
  .field
    = f.label :url, 'Wo man Dich im Internet findet'
    = f.text_field :url, placeholder: 'http://twitter.com/hanna_muster'
  
  .actions
    = f.submit 'Ändern', class: 'button'
    &nbsp;&nbsp;
    = cancel_action
  

app/views/accounts/_form_email_pass.html.haml
= form_with model: account, local: true do |f|
  - if account.errors.any?
    #error_explanation
      %h2= "#{pluralize(account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |message|
          %li= message
        
      
    
  
  .field
    = f.label :email, 'Deine E-Mail Adresse'
    = f.text_field :email, placeholder: 'hanna.muster@meins.de'
  
  .field
    = f.label :password, 'Such Dir ein Kennwort aus'
    = f.password_field :password
  
  .field
    = f.label :password_confirmation, 'Bitte Kennwort nochmals bestätigen'
    = f.password_field :password_confirmation
  
  .actions
    = f.submit 'Anlegen', class: 'button'
  

app/views/accounts/edit.html.haml
.content
  %h5 Deinen Account bearbeiten
  
  = render partial: 'form', locals: { account: @account, cancel_action: link_to( 'Abbrechen', @account ) }

app/views/accounts/index.html.haml
.content
  - unless alert.blank?
    .callout.warning
      %p= alert
  
  - unless notice.blank?
    .callout.success
      %p= notice
    
  
  %h4 Autorinnen und Autoren
  
  %ul.accounts_list
    - @accounts.each do |account|
      %li.account_preview
        = link_to account.name || 'unbekannt', account, class: 'name'
        
        = h_markdown truncate( account.description, length: 150 )
      
    
  

app/views/accounts/new.html.haml
.content
  %p.help
    Damit wir Deine Beiträge hier speichern können, solltest Du Dir kurz einen Login einrichten. Es tut nicht weh, im Gegenteil, es hilft... ;-)
  
  %p= link_to 'Hab schon einen Login &raquo;'.html_safe, login_path
  
  %br
  %h5 Neuen Login für dich anlegen
  
  = render 'form_email_pass', account: @account

app/views/accounts/show.html.haml
- h_user_nav
- h_title [ @account.name, 'Autor*in bei skribi' ].compact.join( ' - ' )
- h_description @account.description

.content
  - unless alert.blank?
    .callout.warning
      %p= alert
  
  - unless notice.blank?
    .callout.success
      %p= notice
    
  
  %h4= @account.name_text
  
  = h_markdown @account.description
  
  - unless @account.url.blank?
    %p= link_to 'Im Internet...', @account.url
  
  - if current_account == @account
    %p= link_to 'Bearbeiten', edit_account_path( @account )
  
  %br
  - if @account.chapters.published.size > 0
    %h5
      = @account.chapters.published.size
      veröffentlichte Kapitel von
      = @account.name || 'unbekannt'
    
    = render 'chapters/chapter_list', chapters: @account.chapters.published
  
  %br
  - if current_account == @account and @account.chapters.drafted.size > 0
    %h5
      = pluralize @account.chapters.drafted.size, 'entworfene'
      Kapitel von
      = @account.name || 'unbekannt'
    
    .drafted
      = render 'chapters/chapter_list', chapters: @account.chapters.drafted
    
  